# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CcmcRN' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CcmcRN

	pod 'React', :path => '../node_modules/react-native', :subspecs => [
	  'Core',
	  'RCTImage',
	  'RCTNetwork',
	  'RCTText',
	  'RCTWebSocket',
	  'RCTAnimation',
      'RCTLinkingIOS',
      'ART',
      'RCTActionSheet',
      'RCTGeolocation',
      'RCTNetwork',
      'RCTSettings',
      'RCTVibration',
      'RCTCameraRoll', #For camera roll picker
	]
    
    pod 'GoogleMaps'
    
    pod 'react-native-material-kit', :path => '../node_modules/react-native-material-kit'
    
#    pod 'react-native-maps', :path => '../node_modules/react-native-maps'
#    
#    pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'

    pre_install do |installer|
        def installer.verify_no_static_framework_transitive_dependencies; end
    end

end
